<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Registro</title> 
  <?php include('local/resources/views/includes/referencias_top.html');?>
 
   <link href="local/resources/views/plugins/select2/select2.css" rel="stylesheet" /> 
 <script type="text/javascript" src="https://code.jquery.com/jquery-2.0.2.js"></script> 
   <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
   <script type="text/javascript" src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
   <script src="http://code.sigasoft.com.br/sweetalert2/dist/sweetalert2.min.js"></script> 
  <style type="text/css">  
  .ui-menu .ui-menu-item .ui-menu-item-icon {
      background-repeat: no-repeat;
      background-position: 2px, 0;
      background-size: 16px;
      padding-left: 23px;
  }
    </style>
    

  <script type="text/javascript">//<![CDATA[

(function( $ ) {
    
    // Extend the autocomplete widget, using our own application namespace.
    $.widget( "app.autocomplete", $.ui.autocomplete, {

        // The _renderItem() method is responsible for rendering each
        // menu item in the autocomplete menu.
        _renderItem: function( ul, item ) {

            // We want the rendered menu item generated by the default implementation.
            var result = this._super( ul, item );

            // If there is logo data, add our custom CSS class, and the specific
            // logo URL.
            if ( item.logo ) {
                result.find( "a" )
                      .addClass( "ui-menu-item-icon" )
                      .css( "background-image", "url(" + item.logo + ")" );
            }

            return result;

        }

    });

})( jQuery );

$(function() { 
    $( "#pais" ).autocomplete({
        source: [

         <?php 
            foreach ($datos as $key ) { 
              echo '{
                label: "'.$key->nombrePais.'",
                logo: "local/resources/views/img/bandera/'.$key->iso.'.png",
            },';
            }
          ?>  
        ]
    }); 
});
  
</script> 

<script type="text/javascript">
  
  function validar_formulario()
  {
    if($("#nombre").val()=="")
    { 
        swal("Atención!", "Coloque un nombre de usuario o correo", "info");
        $("#nombre").focus();        
    }
    else if($("#clave1").val()=="")
    {
     
        swal("Atención!", "Debe colocar una clave.", "info");
        $("#clave1").focus();
    }
     else if($("#clave2").val()=="")
    {
        
        swal("Atención!", "Por favor, coloque de nuevo su clave.", "info");
        $("#clave2").focus();
    }
    else if($("#clave1").val() != $("#clave2").val())
    {
   
      swal("Atención!", "Las claves deben ser iguales.", "error");
    }
    else if($("#correo").val()=="")
    {
      
      swal("Atención!", "Debe debe completar el correo electrónico.", "info");
      $("#correo").focus();
    }
    else if($("#pais").val()=="")
    { 
      alert($("#pais").val());
      swal("Atención!", "Debe seleccionar su país ", "info");
      $("#pais").focus();
    }
     else if($("#fecha").val()=="")
    {
      
      swal("Atención!", "Debe colocar su fecha de nacimiento.", "info");
      $("#fecha").focus();
    }
     else if($("#sexo").val()=="")
    {
      
      swal("Atención!", "Debe seleccionar su sexo", "info");
      $("#sexo").focus();
    }
    else if($('#politicas').prop('checked')==false)
    { 
      swal("Atención!", "Debe aceptar las políticas de opinion.", "info");
      $("#politicas").focus();
    }
    else
    {
      $("#formulario").submit();
    }
  } 
</script>
</head>
<body class="hold-transition register-page" style="background-image: url('https://www.ibm.com/blogs/business-analytics/wp-content/uploads/2017/02/data-analytics-too-much-data.jpg');">

  

<div class="register-box">
  <div class="register-logo">
    <a href="iniciar"><b>Opinion</b>App</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">Complete la información solicitada.</p>

    <form action="registro" method="post" id="formulario">
    <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
      <div class="form-group has-feedback">
        <input name="nombre" id="nombre" type="text" class="form-control" placeholder="Usuario">
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
       <div class="form-group has-feedback">
        <input name="clave1" id="clave1" type="password" class="form-control" placeholder="Clave">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input name="clave2" id="clave2" type="password" class="form-control" placeholder="Repita su clave">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input name="correo" id="correo" type="email" class="form-control" placeholder="Correo">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div> 
      <div class="form-group has-feedback">
      <input name="pais" placeholder="pais" id="pais" class="ui-widget ui-widget-content ui-autocomplete-input form-control" autocomplete="off"> 
         
      </div>
       <div class="form-group has-feedback">
        <input name="fecha" id="fecha" type="date" class="form-control" placeholder="Fecha de nacimiento"  >
        <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
      </div>
     <div  class="form-group has-feedback">
        <select name="sexo" id="sexo" class="form-control" s>
          <option value="">Sexo</option>
          <option value="F">Femenino</option>
          <option value="M">Masculino</option>
        </select> 
      </div>
      <div class="row">         
       <div class="col-xs-12" style="padding-top: 0px;"> 
          <input name="politicas" type="checkbox" class="form-check-input" id="politicas" style="margin-top: -30px;margin-bottom: 15px;">
          <span style="margin-top: -10px;">Acepto las <a href="http://www.opinion-app.com/politicadeprivacidad.pdf" target="_blank">politicas de opinionApp</a></span> 
       </div>
        <div class="col-xs-12 text-center">
          <a onClick="validar_formulario()" class="btn btn-primary btn-block btn-flat">Registrar</a>
        </div>
        <div class="col-xs-12" style="padding-top: 10px;">    
          <a  href="iniciar" class="" style="margin-top: 15px;">Iniciar sesión</a>
        </div>
        <!-- /.col -->
      </div>
    </form> 
  </div>
  <!-- /.form-box -->
  <div id="ohsnap"></div> 
</div>
<!-- /.register-box -->
 
 <?php
 if(isset($_GET["info"]))
  {
    if($_GET["info"]=="nombre") echo '<script>swal("Atención!", "Debe indicar su nombre de usuario.", "info");</script>';
    else if($_GET["info"]=="correo") echo '<script>swal("Atención!", "Debe indicar un correo.", "info");</script>';
    else if($_GET["info"]=="pais") echo '<script>swal("Atención!", "Debe seleccionar un país.", "info");</script>';
    else if($_GET["info"]=="clave1") echo '<script>swal("Atención!", "Debe indicar una clave.", "info");</script>';
    else if($_GET["info"]=="max") 
    {
      echo '<script>swal("Atención!", "La clave debe ser mayor o igual a 6 caractéres.", "info");</script>';
    }
    else if($_GET["info"]=="clave2") echo 'Por favor repita su clave.';
    else if($_GET["info"]=="claves") echo '<script>swal("Atención!", "Las claves deben ser iguales", "error");</script>';
    else if($_GET["info"]=="sexo") echo '<script>swal("Atención!", "Debe indicar su sexo.", "info");</script>';
    else if($_GET["info"]=="fecha") echo '<script>swal("Atención!", "Debe indicar su fecha de nacimiento.", "info");</script>';
    else if($_GET["info"]=="politicas") echo '<script>swal("Atención!", "Debe aceptar las políticas.", "info");</script>';
     else if($_GET["info"]=="true") {echo '<script>swal("Atención!", "Se ha enviado un correo para la activación de su cuenta.", "info");</script>';}

  }
   if(isset($_GET["validate"]))
  {
    if($_GET["validate"]=="correo")
    {
      echo '<script>swal("Atención!", "Este correo ya esta siendo usado en otra cuenta.", "error");
     </script>';
    }

     if($_GET["validate"]=="pais")
    {
      echo '<script>swal("Atención!", "Coloque un país válido", "error");
     </script>';
    }
    else if($_GET["validate"]=="usuario")
    {
         echo '<script>swal("Atención!", "Este usuario ya esta siendo usado en otra cuenta.", "error");
     </script>';
    }
  }  
 ?> 
<script src="local/resources/views/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>
